config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "home#show", as: :home
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :messages, only: [:create]

  root to: "dashboards#show"

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @users = User.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    # Pusher['test_channel'].trigger('my_event', {
    #         message: "lookit Linda"
    # })
    @new_message = params[:message]

    render partial: "dashboards/message", locals: { new_message: @new_message }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/_message.html.erb
<% Pusher['test_channel'].trigger('my_event', { message: new_message }) %>

app/views/dashboards/show.html.erb
<head>
  <title>Pusher Test</title>
    <script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    Pusher.log = function(message) {
      if (window.console && window.console.log) {
        window.console.log(message);
      }
    };

    var pusher = new Pusher('b922b9271e3bba9bb80b');
    var channel = pusher.subscribe('test_channel');
    channel.bind('my_event', function(data) {
      console.log("Did you make it?");
      $("#message-list").append("<p>"+data.message+"</p>");
      return false;
    });
  </script>
</head>


<h1><%= current_user.email %>'s Dashboard</h1>

<h3>User List</h3>
<ul id="user-list">
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

<h3>Message a Friend</h3>
<section id="send-message">

  <%# <%= button_to "Send lookit Message", messages_path, remote: true  %>
  <%= form_tag messages_path, remote:true do %>
    <%= text_field_tag :message %>
    <%= submit_tag %>
  <% end %>

</section>


<h3>Your Messages</h3>
<section id="message-list">

  <% if @new_message.nil? %>

  <% else %>
    <%= render partial: "dashboards/message", locals: { new_message: @new_message } %>
  <% end %>

</section>

app/views/home/show.html.erb
<h1>Welcome to the LookIt App</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lookit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if signed_in? %>
    <%= link_to "Sign out", session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_session_path %>
    <i> - or - </i>
    <%= link_to "Sign up", new_user_path %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>